server:
  port: 8761

eureka:
    client:    register-with-eureka: false
    fetch-registry: false

spring:
  application:    name: eurekaServer  config:
    import: optional:configserver:http://localhost:8888
logging:
  config: ${microservice.log.config}
  